seed_everything: 0
trainer:
  max_epochs: 500
model:
  embed_dim: 256
  image_resolution: 256
  vision_layers: 'dino_vit16'
  vision_width: 128
  vision_patch_size: 32
  in_channels: 12
  le_type: 'sphericalharmonics'
  pe_type: 'siren'
  frequency_num: 32
  max_radius: 0.001
  min_radius: 1e-05
  legendre_polys: 10
  harmonics_calculation: 'analytic'
  sh_embedding_dims: 40
  learning_rate: 1e-4
  weight_decay: 0.01
  num_hidden_layers: 2
  capacity: 512
data:
  data_dir: ./data/s2
  batch_size: 512
  num_workers: 24
  val_random_split_fraction: 0.1
  crop_size: 224
  transform: 'pretrained'
  mode: 'both'
watchmodel: True
